app/spotify/forms.py
from flask_wtf import FlaskForm


class SpotifyForm(FlaskForm):
    pass


class NullForm(FlaskForm):
    pass

app/spotify/__init__.py
from flask import Blueprint
from app import Config
from app.spotify.classes import SpotifyAPI

bp = Blueprint('spotify', __name__)

sp = SpotifyAPI(Config.SPOTIFY_CLIENT_ID, Config.SPOTIFY_CLIENT_SECRET, Config.SPOTIFY_REDIRECT_URL)

from app.spotify import routes

app/spotify/routes.py
from datetime import datetime, timedelta
from flask import render_template, flash, redirect, url_for, request, session, current_app
from flask_login import login_user, current_user
from app import db
from app.spotify import bp, sp
from app.spotify.forms import SpotifyForm
from app.spotify.functions import search_spotify_and_save
from app.user.classes import get_avatar
from app.models import User, ComposerList, Spotify, WorkAlbums, WorkList
import jsonpickle
from wtforms import SubmitField, RadioField
import base64
import hashlib
from sqlalchemy.orm import load_only
from sqlalchemy.sql import func
import random


@bp.route('/connect_spotify')
def connect_spotify():
    url = sp.authorize()
    return redirect(url)


@bp.route('/spotify')
def spotify():

    # get access token
    code = request.args.get('code')
    response = sp.get_token(code)
    if response == "INVALID":
        flash("Could not connect to Spotify.")
        return render_template('errors/flash.html')
    session['spotify_token'] = response.json()['access_token']
    session['refresh_token'] = response.json()['refresh_token']
    session['spotify_token_expire_time'] = datetime.now() + timedelta(hours=1)

    # get playback devices
    session['available_devices'] = sp.get_devices()
    if session['available_devices'] == "INVALID":
        session['available_devices'] = None
        flash("Could not connect to Spotify.")
        return render_template('errors/flash.html', title="Error")
    return redirect(url_for('spotify.spotify_form'))


@bp.route('/spotify_form', methods=['GET', 'POST'])
def spotify_form():
    session['spotify_device'] = ""
    if current_user.is_authenticated:
        pass
    else:
        response = sp.get_user()
        info = response.json()
        try:
            session['userid'] = info['id']
            _id = info['id'] + current_app.config['SECRET_KEY']
        except KeyError:
            flash("Could not connect to Spotify.")
            return render_template('errors/flash.html')

        if info['product'] == "premium":
            session['premium'] = True
        else:
            session['premium'] = False

        hasher = hashlib.sha1(_id.encode('utf-8'))
        username = base64.urlsafe_b64encode(hasher.digest()[:10]).decode('utf-8')
        username = ''.join(e for e in username if e.isalnum()).upper()
        user = User.query.filter_by(username=username).first()
        if user is None:
            display_name = info['display_name']
            try:
                image_url = info['images'][0]['url']
                response = get_avatar(username, image_url)
                image = response[0]
            except:
                image = None

            duplicateuser = User.query.filter_by(display_name=display_name).first()
            if duplicateuser:
                display_name = display_name + str(random.randint(1, 999))

            user = User(username=username, email=username + "@none.com", display_name=display_name, img=image)
            user.set_password(username)
            db.session.add(user)
            db.session.commit()
            login_user(user)
        login_user(user)

    devicelist = session['available_devices']
    # check if there are any devices, show form if so
    if not session['premium']:
        flash("Note: In-browser playback requires Spotify premium. With a free account, clicking on album tracks will link to the track in Spotify rather than play them directly.")
        return render_template('spotify/spotify_free.html')

    if len(devicelist) == 0:
        flash("Error: no active Spotify playback devices found.")
        form = SpotifyForm()
        return render_template('spotify/spotify_form.html', form=form)
    else:
        devices = {}
        for i in range(0, len(devicelist)):
            devices[devicelist[i]['id']] = devicelist[i]['name']
        choices = []
        for device in devices:
            choices.append((device, devices[device]))
        setattr(SpotifyForm, 'device', RadioField("device", choices=choices, default=choices[0][0]))
        setattr(SpotifyForm, 'test', SubmitField('Test'))
        setattr(SpotifyForm, 'submit', SubmitField('Select'))

    form = SpotifyForm()
    if form.validate_on_submit():
        session['spotify_device'] = form.device.data
        session['available_devices'] = []  # necessary for form to display properly
        del form.device
        return redirect(session['previouspage'])
    return render_template('spotify/spotify_form.html', form=form, title="Select Spotify Device")


@bp.route('/play_spotify', methods=['GET', 'POST'])
def play_spotify():
    # plays music for composer preview if a token exists
    if session['premium'] and session['autoplay']:
        _id = request.form['id']
        composer = ComposerList.query.filter_by(id=_id).first()
        spotify_track = composer.spotify
        if spotify_track:
            response = sp.play_from_database(spotify_track)
        else:
            response = sp.search_and_play(composer.name_full)
        return str("Premium")
    elif session['premium'] and not session['autoplay']:
        return str("Premium")
    else:
        _id = request.form['id']
        composer = ComposerList.query.filter_by(id=_id).first()
        preview_url = composer.preview_music
        return str(preview_url)


@bp.route('/play_spotify_preview_track', methods=['GET', 'POST'])
def play_spotify_preview_track():
    # plays music for composer preview if a token exists
    _id = request.form['id']
    preview_url = sp.get_track_preview(_id)
    print(preview_url)
    if preview_url is not None:
        return str(preview_url)
    return "No spotify preview available", 404


@bp.route('/pause_spotify', methods=['GET', 'POST'])
def pause_spotify():
    if session['premium'] and session['autoplay']:
        response = sp.pause()
        return str(response)
    return "No spotify token or autoplay off."


@bp.route('/unplay_spotify', methods=['GET', 'POST'])
def unplay_spotify():
    if session['premium']:
        response = sp.pause()
        return str(response)
    return "No spotify token."


@bp.route('/unpause_spotify', methods=['GET', 'POST'])
def unpause_spotify():
    if session['premium']:
        response = sp.unpause()
        return str(response)
    return "No spotify token."


@bp.route('/test_spotify', methods=['GET', 'POST'])
def test_spotify():
    if session['premium']:
        try:
            device = request.form['device']
            spotify_track = '{"uris": ["spotify:track:2q7eAC2QXXNLaEBQZfWgG5"]}'
            response = sp.test(device, spotify_track)
            return str(response)
        except:
            return "Invalid spotify token."
    return "No spotify token."


@bp.route('/search_spotify', methods=['GET', 'POST'])
def search_spotify():
    # doesn't actually search spotify anymore (moved searching to cron tasks)
    _id = request.form['id']

    existingspotify = Spotify.query.filter_by(id=_id).first()
    if existingspotify:
        return "Exists"

    return 'No Spotify tracks found.', 404


@bp.route('/play_track', methods=['GET', 'POST'])
def play_track():

    _id = request.form['id']
    urilist = {}
    urilist['uris'] = _id.split()
    jsonlist = jsonpickle.encode(urilist)

    first_track_id = urilist['uris'][0].replace("spotify:track:", "")

    if session['premium']:
        response = sp.play_track(jsonlist)
        trackjson = sp.get_track(first_track_id)
        track = trackjson.json()
        track_length = track['duration_ms']
        return str(track_length)
    return "Connect with Spotify to play tracks.", 403


@bp.route('/seek_track', methods=['GET', 'POST'])
def seek_track():

    position = request.form['position']

    if session['premium']:
        response = sp.seek_to_position(position)
        response2 = sp.unpause()
        return str(response)
    return "Connect with Spotify to play tracks.", 403


@bp.route('/next_track')
def next_track():

    response = sp.next()
    trackjson = sp.current_track()
    track = trackjson.json()
    track_length = track['item']['duration_ms']
    return str(track_length)


@bp.route('/previous_track')
def previous_track():

    response = sp.previous()
    trackjson = sp.current_track()
    track = trackjson.json()
    track_length = track['item']['duration_ms']
    return str(track_length)


@bp.route('/get_playlists')
def get_playlists():
    if session['spotify_token']:
        try:
            # first get user's profile info
            response = sp.get_user()
            userid = response.json()['id']
            session['userid'] = userid

            # then get user's playlists
            response = sp.get_playlists()
            playlists = response.json()['items']

            playlistlist = []
            reverse_dict = {}
            for playlist in playlists:
                playuserid = playlist['owner']['id']
                if playuserid == userid:
                    playlistlist.append(playlist['name'])
                    reverse_dict[playlist['name']] = playlist['id']

            session['user_playlists'] = reverse_dict
            return jsonpickle.encode(playlistlist)
        except:
            return "Error with token.", 500
    return "Connect with Spotify to create and add music to playlists.", 403


@bp.route('/playlist_add')
def playlist_add():

    if session['spotify_token']:
        new_playlist = request.args.get('new-playlist')
        existing_playlist = request.args.get('existing-playlist')
        tracks = request.args.get('tracks')

        if len(tracks) == 2:  # if [] is empty
            flash("Error: No tracks were selected.", "danger")
            return redirect(session['thispage'])

        if new_playlist:
            playlist_name = new_playlist
            try:
                response = sp.create_playlist(new_playlist)
                playlist_id = response.json()['id']
            except:

app/templates/spotify/_composerplaylistmodal.html
<div class="modal fade" id="composerplaylistmodal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><b>Composer Playlist Generator</b></h5>
        </button>
      </div>
      <div class="modal-body">
        <p>Use this form to generate a playlist consisting of a random selection of works for {{works[0].composer}}.</p>
        <form action="/composer_playlist" method="get" name="playlistform">
          <div class="form-group">
            <label for="exampleFormControlInput1">Playlist name</label>
            <input type="text" class="form-control" name="name" id="new-playlist" value="A Taste of {{works[0].composer}}" required>
            <input type="hidden" id="composer" name="composer" value="{{works[0].composer}}">
          </div>
          <div class="form-group">
<label for="popularity">Work Grouping</label><br>
<label class="radio-inline"><input type="radio" value="tracks" name="grouping" checked>Random movements</label>
<label class="radio-inline"><input type="radio" value="works" name="grouping">Complete Works</label><br><br>
<label for="popularity">Popularity</label><br>
<label class="radio-inline"><input type="radio" value="all" name="popularity" checked>All Works</label>
<label class="radio-inline"><input type="radio" value="recommend" name="popularity">Most Recommended</label>
<label class="radio-inline"><input type="radio" value="obscure" name="popularity">Less Popular</label><br><br>
<label for="popularity">Operas</label><br>
<label class="checkbox-inline"><input type="checkbox" name="operas" value="True">Include Operas</label>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Generate Playlist</button></form>
      </div>
    </div>
  </div>
</div>

app/templates/spotify/_createplaylistmodal.html
<div class="modal fade" id="createplaylistmodal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><b>Add to Spotify Playlist</b></h5>
        </button>
      </div>
      <div class="modal-body">
        <form action="/playlist_add" method="get" name="playlistform">
          <div class="form-group">
            <label for="exampleFormControlSelect1">Add to Existing Playlist</label>
            <select class="form-control" name="existing-playlist" id="existing-playlist">
            </select>
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput1">Create New Playlist</label>
            <input type="text" class="form-control" name="new-playlist" id="new-playlist" placeholder="Playlist Name">
            <input type="hidden" id="tracks" name="tracks" value="1">
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Submit to Spotify</button></form>
      </div>
    </div>
  </div>
</div>

app/templates/spotify/_footer.html
<style>
.footertableclass{
  border-collapse: collapse;
  width: 100%;
}

.footertable {
  border: 0px solid #e3e6e8;
  text-align: center;
  padding: 0px;
/*  height: 0px;*/
  vertical-align: middle;
}

.controls{
    text-align: left !important;
}

.autoplay{
    text-align: right !important;
}

.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 6px;
  background: #6a7682;
  outline: none;
  opacity: 0.8;
  -webkit-transition: .2s;
  transition: opacity .2s;
  cursor: pointer;
  border-radius: 3px;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 12px;
  height: 12px;
  background: #fff;
  cursor: pointer;
  border-radius: 50%;
}

.slider::-moz-range-thumb {
  width: 12px;
  height: 12px;
  background: #fff;
  cursor: pointer;
  border-radius: 50%;
}

.playback-button{
 margin: 0px !important;
}

.title{
    vertical-align: bottom;
    height: 35px;
}

#composition-play{
    font-size: 12px;
}

.album-play-pic{
  /*margin-top: 4px;*/
  height: 20px;
  object-fit: cover;
  width: 20px;
  padding: 0px !important;
}
.regular-checkbox{
    filter: grayscale(1);
}

</style>
{% if session['premium'] %}
<div class="footer navbar-fixed-bottom">
    <div class="container">
    <table class="footertableclass">
    <tr class="composition-header"><td class="footertable title" width="100%">
    <img id="album-img-playback" class="album-play-pic" src="" hidden>&nbsp
    <span id="composition-play"></span>
    </td></tr>
    </table>
<table class="footertableclass">
  <tr>
    <td class="footertable controls" width="20%">
        <form id = "controls-form">
            <button id="previous-btn" type="button" onclick="previousspotify()" class="btn btn-default filter-button playback-button"> <span id="next" class="glyphicon glyphicon-step-backward"> </span></button>
            <button id="play-btn" type="button" onclick="unpausespotify()" class="btn btn-default filter-button playback-button" hidden> <span id="pauseplay" class="glyphicon glyphicon-play"> </span></button>
            <button id="pause-btn" type="button" onclick="unplayspotify()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-pause"> </span></button>
            <button id="next-btn" type="button" onclick="nextspotify()" class="btn btn-default filter-button playback-button"> <span id="next" class="glyphicon glyphicon-step-forward"> </span></button>
        </form>
    </td>

    <td class="footertable" width="10%"><span id="time-progress">00:00</span></td>
    <td class="footertable" width="40%">
        <div class="slidecontainer">
            <input type="range" min="0" max="100" value="0" class="slider" id="progressbar" oninput="holdrange(this.value)" onchange="seekspotify(this.value)">
        </div>
    </td>
    <td class="footertable" width="10%"><span id="time-duration">00:00</span></td>
    <td class="footertable autoplay" width="20%">

                <label class="checkbox-inline">
                {% if autoplay: %}
                <input type="checkbox" class="regular-checkbox" id="autoplay" name="autoplay" value="True" checked>Autoplay
                {% endif %}
                {% if not autoplay: %}
                <input type="checkbox" class="regular-checkbox" id="autoplay" name="autoplay" value="True">Autoplay
                {% endif %}
                </label>

    </td>
  </tr>
</table>
</div>
</div>
{% else %}

<div class="footer navbar-fixed-bottom">
    <div class="container">
    <table class="footertableclass">
    <tr class="composition-header"><td class="footertable title" width="100%">
    <span id="composition-play">Preview mode: Log in with your Spotify Premium account to play full tracks</span>
    </td></tr>
    </table>
<table class="footertableclass">
  <tr>
    <td class="footertable controls" width="20%">
        <form id = "controls-form">
            <button type="button" onclick="" class="btn btn-default filter-button playback-button" disabled> <span id="next" class="glyphicon glyphicon-step-backward"> </span></button>
             <button id="play-btn" type="button" onclick="resumespotifypreview()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-play"> </span></button>
            <button id="pause-btn" type="button" onclick="pausespotifypreview()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-pause"> </span></button>
            <button type="button" onclick="" class="btn btn-default filter-button playback-button" disabled> <span id="next" class="glyphicon glyphicon-step-forward"> </span></button>
        </form>
    </td>

    <td class="footertable" width="10%"><span id="time-progress">00:00</span></td>
    <td class="footertable" width="40%">
        <div class="slidecontainer">
            <input type="range" min="0" max="30000" value="0" class="slider" id="progressbar" oninput="holdrange(this.value)" onchange="seekpreview(this.value)">
        </div>
    </td>
    <td class="footertable" width="10%"><span id="time-duration">00:30</span></td>
    <td class="footertable autoplay" width="20%">

                <label class="checkbox-inline">
                <input type="checkbox" class="regular-checkbox" id="" name="autoplay" value="False" disabled>Autoplay
                </label>

    </td>
  </tr>
</table>
</div>
</div>
{% endif %}

app/templates/spotify/_footer_mobile.html
<style>
.footertableclass{
  border-collapse: collapse;
  width: 100%;
}

.footertable {
  border: 0px solid #e3e6e8;
  text-align: center;
  padding: 3px;
  vertical-align: middle;

}

.controls{
    text-align: center !important;
}

.autoplay{
    text-align: right !important;
}

.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 6px;
  background: #6a7682;
  outline: none;
  opacity: 0.8;
  -webkit-transition: .2s;
  transition: opacity .2s;
  cursor: pointer;
  border-radius: 3px;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 12px;
  height: 12px;
  background: #fff;
  cursor: pointer;
  border-radius: 50%;
}

.slider::-moz-range-thumb {
  width: 12px;
  height: 12px;
  background: #fff;
  cursor: pointer;
  border-radius: 50%;
}

.playback-button{
 margin: 0px !important;
}

.title{
    vertical-align: bottom;
    height: 45px;
}

#composition-play{
    font-size: 12px;
}


.album-play-pic{
  /*margin-top: 4px;*/
  height: 20px;
  object-fit: cover;
  width: 20px;
  padding: 0px !important;
}

.footertable
{
  height: 30px;
}
#controls-form{
  margin: 0px !important;
}

.autoplay{
    font-size: 12px;
}

.regular-checkbox{
    filter: grayscale(1);
}

/*mobile button select color*/
button:hover {
  background-color: rgb(52, 58, 64, 1)!important;
  border: none;
  color: white!important;
  margin-bottom: 8px;
  margin-top: 8px;
}


</style>
{% if session['premium'] %}
<div class="footer navbar-fixed-bottom">
    <div class="container">
  <table class="footertableclass">
    <tr class=""><td class="footertable" width="100%">
    <img id="album-img-playback" class="album-play-pic" src="" hidden>&nbsp
    <span id="composition-play"></span>
    </td></tr>
    </table>
  <table class="footertableclass">
    <tr>
    <td class="footertable" width="15%"><span id="time-progress">00:00</span></td>
    <td class="footertable" width="70%">
        <div class="slidecontainer">
            <input type="range" min="0" max="100" value="0" class="slider" id="progressbar" oninput="holdrange(this.value)" onchange="seekspotify(this.value)">
        </div>
    </td>
    <td class="footertable" width="15%"><span id="time-duration">00:00</span></td>
  </tr>
  </table>
<table class="footertableclass">
  <tr>
<td class="footertable controls" width="25%"></td>

    <td class="footertable controls" width="50%">
        <form id = "controls-form">
            <button id="previous-btn" type="button" onclick="previousspotify()" class="btn btn-default filter-button playback-button"> <span id="next" class="glyphicon glyphicon-step-backward"> </span></button>
            <button id="play-btn" type="button" onclick="unpausespotify()" class="btn btn-default filter-button playback-button" hidden> <span id="pauseplay" class="glyphicon glyphicon-play"> </span></button>
            <button id="pause-btn" type="button" onclick="unplayspotify()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-pause"> </span></button>
            <button id="next-btn" type="button" onclick="nextspotify()" class="btn btn-default filter-button playback-button"> <span id="next" class="glyphicon glyphicon-step-forward"> </span></button>
        </form>
    </td>
<td class="footertable autoplay" width="25%">

                <label class="checkbox-inline">
                {% if autoplay: %}
                <input type="checkbox" class="regular-checkbox" id="autoplay" name="autoplay" value="True" checked>Autoplay
                {% endif %}
                {% if not autoplay: %}
                <input type="checkbox" class="regular-checkbox" id="autoplay" name="autoplay" value="True">Autoplay
                {% endif %}
                </label>
    </td>
  </tr>
</table>
</div>
</div>
{% else %}
<div class="footer navbar-fixed-bottom">
    <div class="container">
  <table class="footertableclass">
    <tr class=""><td class="footertable" width="100%">
<span id="composition-play">Log in with your Spotify Premium account to play full tracks</span>
    </td></tr>
    </table>
  <table class="footertableclass">
    <tr>
    <td class="footertable" width="15%"><span id="time-progress">00:00</span></td>
    <td class="footertable" width="70%">
        <div class="slidecontainer">
            <input type="range" min="0" max="30000" value="0" class="slider" id="progressbar" oninput="holdrange(this.value)" onchange="seekpreview(this.value)">
        </div>
    </td>
    <td class="footertable" width="15%"><span id="time-duration">00:30</span></td>
  </tr>
  </table>
<table class="footertableclass">
  <tr>
<td class="footertable controls" width="25%"></td>

    <td class="footertable controls" width="50%">
        <form id = "controls-form">

            <button id="play-btn" type="button" onclick="resumespotifypreview()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-play"> </span></button>
            <button id="pause-btn" type="button" onclick="pausespotifypreview()" class="btn btn-default filter-button playback-button"> <span id="pauseplay" class="glyphicon glyphicon-pause"> </span></button>

        </form>
    </td>
<td class="footertable autoplay" width="25%">


    </td>
  </tr>
</table>
</div>
</div>
{% endif %}

app/templates/spotify/_getspotifymodal.html
<div class="modal fade" id="getspotifymodal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><b>Spotify Connect</b></h4>
        </button>
      </div>
      <div class="modal-body">
        <p>Sign in with your Spotify account to listen to albums, create playlists, and engage with the community. In-browser music playback requires Spotify Premium.</p>
        <br>
        <b>Your Privacy is Important.</b> Your email address is <b>not</b> collected from Spotify. Only your public display name and profile picture are stored. These can be changed or deleted from your Profile page after logging in.
        Your Spotify ID and other data is not stored or made public.
      <br><br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{{ url_for('spotify.connect_spotify') }}" type="button" class="btn btn-success">Connect to Spotify</a>
      </div>
    </div>
  </div>
</div>

app/templates/spotify/spotify_form.html
{% extends "base.html" %}
{% block scripts %}
{{super()}}
<script type="text/javascript">
    function testspotify(device) {

        $.ajax({
            url: '/test_spotify',
            data: {
                device: device
            },
            type: 'POST',
            success: function(res) {
                console.log(res);
            },
            error: function(error) {
                console.log(error);
            }
        });
    }

    $(document).ready(function() {
        $('#test').removeAttr("type").attr("type", "button");
        $('#submit').addClass( "btn-primary" );
        $('#test').on('click', function(e) {
        var device = $("input[name=device]:checked").val();
        testspotify(device);
        });
    });
</script>
{% endblock %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<style>
body {
    background-color: #f0f3f4;
}
</style>
<h2>Welcome, {{current_user.display_name.split()[0]}}!</h2>
<p>With your Spotify Premium account, you can take control of your music directly from your browser. Spotify will play in the background.</p>

<div class="panel panel-default">
  <div class="panel-heading">Select Spotify Playback Device:</div>
  <div class="panel-body">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning" role="alert">{{ message }}
        </div>
<p><a href="spotify:track:6cUCckpdlqHJ5Ascf2uH2A">Open the Spotify app <span class="glyphicon glyphicon-share" aria-hidden="true"></span> </a> in the background, <a href="https://open.spotify.com/" target="_blank">use the web player</a>, or open Spotify on another device you wish to play to.</a></p>
<p><b>If Spotify is open:</b> Spotify may sometimes fall asleep. Go to the Spotify app and wake it by playing any track.</p>
<hr>
<a class="btn btn-primary" href="{{ url_for('spotify.connect_spotify') }}" role="button">Click to Try Again</a>
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% with messages = get_flashed_messages() %}
    {% if not messages %}
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
        <br><b>Test</b> should play a brief jingle.
    </div>
</div>
<hr>
<p>Device not listed? Open Spotify on the device and <a href="{{ url_for('spotify.connect_spotify') }}">click here to try again.</a></p>
Spotify open but <b>Test</b> has no audio? Spotify may sometimes fall asleep. Go to the Spotify app and wake it by playing any track.
    {% endif %}
    {% endwith %}
  </div>
</div>


{% endblock %}

app/templates/spotify/spotify_free.html
{% extends "base.html" %}
{% block scripts %}
{{super()}}
{% endblock %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<h2>Welcome, {{current_user.display_name.split()[0]}}!</h2>
<style>
body {
    background-color: #f0f3f4;
}
</style>

<div class="panel panel-default">
  <div class="panel-body">
    Your musical journey awaits. <a href="/"> Get started</a>.
  </div>
</div>



    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% endwith %}



{% endblock %}

app/templates/spotify/spotify_login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endwith %}
<style>
body {
    background-color: #f0f3f4;
}
</style>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Log In</h3>
  </div>
  <div class="panel-body">
    <p>Connect with your Spotify account to listen to albums, create playlists, and engage with the community.</p>

     <h5><b>Your Privacy is Important</b></h5>
        <p>Your email address is <b>not</b> collected from Spotify. Only your public display name and profile picture are stored. These can be changed or deleted from your Profile page after logging in.
        Your Spotify ID and other data is not stored or made public.</p><hr>
  <a href="/connect_spotify" type="button" class="btn btn-success">Log in with Spotify</a>
  </div>
</div>



{% endblock %}