app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField, FileField
from wtforms.validators import ValidationError, DataRequired, Length
from app.models import User
from app.user.classes import Unique


class EditProfileForm(FlaskForm):
    display_name = StringField('Display Name', validators=[DataRequired(), Length(min=0, max=64), Unique(User, User.display_name)])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')


class ClearVisits(FlaskForm):
    submit = SubmitField('Clear all Visited Works')


class ChangeAvatar(FlaskForm):
    choice = RadioField('Change Profile Picture', choices=[('remove', 'Remove photo'), ('restore', 'Restore Spotify photo'), ('upload', 'Upload image')], default='upload')
    link = StringField('Option 1: Paste URL to image', description='Must be a .jpg or .png file smaller than 5 MB.', validators=[Length(min=0, max=2064)])
    file = FileField('Option 2: Upload an image from device', description='Must be a .jpg or .png file smaller than 5 MB.', validators=[Length(min=0, max=2064)])
    submit = SubmitField('Submit')


class MessageForm(FlaskForm):
    message = TextAreaField('Message', validators=[
        DataRequired(), Length(min=0, max=1400)])
    submit = SubmitField('Submit')

app/composer/__init__.py
from flask import Blueprint

bp = Blueprint('composer', __name__)

from app.composer import routes

app/composer/routes.py
from flask import render_template, redirect, url_for, request, session, abort, flash
from flask_login import current_user
from sqlalchemy.orm import load_only
from app import db
from app.composer import bp
from app.spotify import sp
from app.models import ComposerList, WorkList, Spotify, ArtistAlbums
from app.composer.classes import ComposerHeader, BornDied, Masterpieces
import json
import random
import math


@bp.route('/composer_router/<name>')
def composer_router(name):
    if not session.get('composer_view'):
        if request.MOBILE:
            session['composer_view'] = "tables"
        else:
            session['composer_view'] = "tables"

    if session['composer_view'] == "timeline":
        return redirect(url_for('composer.composer', name=name))

    return redirect(url_for('composer.composerpanels', name=name))


@bp.route('/composer/<name>')
def composer(name):
    session['composer_view'] = "timeline"

    filter_method = request.args.get('filter', "playable")
    search = request.args.get('search', "")

    # check if composer has been catalogued or redirect to albums page
    try:
        work = WorkList.query.filter_by(composer=name).first_or_404()
    except:
        return redirect('/composeralbums/' + name + '/1')

    try:
        # get composer information
        composer = ComposerList.query.filter_by(name_short=name).first_or_404()
    except Exception:
        return redirect(url_for('main.index'))

    # user page viewing
    if current_user.is_authenticated:
        current_user.page_viewing = '<a href="' + url_for("composer.composer", name=name) + '">' + composer.name_full + '</a>'
        db.session.commit()

    # get flag
    with open('app/static/countries.json') as f:
        flags = json.load(f)
    flag = flags[composer.nationality]
    flag = flag.lower()
    composer.flagimg = 'flags/1x1/' + flag + '.svg'

    # get masterpieces
    with open('app/static/masterpieces.json') as f:
        masterpiece_list = json.load(f)

    # create chart
    array = []
    array.append(composer)
    header = ComposerHeader(array, composer.born, composer.died)  # change back
    years = header.generate_dates(composer)
    ages = header.generate_ages(years, composer.born, composer.died)
    eras = header.generate_eras()
    yearlist = list(years.keys())
    borndied = BornDied(composer.born, composer.died, yearlist[0], yearlist[-1])
    master = Masterpieces(masterpiece_list, yearlist[0], yearlist[-1])
    masterpieces = master.generate_masterpieces()
    # retrieve all composer works
    catalogued = []

    if search:
        search_term = "%{}%".format(search)
        filter_method = 'all'
        works = WorkList.query.filter_by(composer=name)\
            .filter(WorkList.genre.ilike(search_term)) \
            .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        if not works:
            works = WorkList.query.filter_by(composer=name)\
                .filter(WorkList.title.ilike(search_term)) \
                .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        if not works:
            works = WorkList.query.filter_by(composer=name)\
                .filter(WorkList.cat.ilike(search_term)) \
                .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        if not works:
            filter_method = 'playable'
            works = db.session.query(WorkList)\
                .join(Spotify, WorkList.id == Spotify.id)\
                .filter_by(composer=name)\
                .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        workspotify = db.session.query(Spotify)\
            .join(WorkList, WorkList.id == Spotify.id)\
            .options(load_only(Spotify.id))\
            .filter_by(composer=name)
        for item in workspotify:
            catalogued.append(item.id)

    else:
        if filter_method == "recommended":
            works = WorkList.query.filter_by(composer=name, recommend=True).order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        elif filter_method == "playable":
            works = db.session.query(WorkList)\
                .join(Spotify, WorkList.id == Spotify.id)\
                .filter_by(composer=name)\
                .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
        else:
            works = WorkList.query.filter_by(composer=name)\
                .order_by(WorkList.order, WorkList.genre, WorkList.date, WorkList.cat, WorkList.id).all()
            workspotify = db.session.query(Spotify)\
                .join(WorkList, WorkList.id == Spotify.id)\
                .options(load_only(Spotify.id))\
                .filter_by(composer=name)
            for item in workspotify:
                catalogued.append(item.id)

    if not works:
        abort(404)

    workslist = header.create_chart(works)

    # for random work
    num = random.randint(0, len(workslist) - 1)
    random_work = workslist[num].id

    # get list of which works has_visited
    visitlist = []
    if current_user.is_authenticated:
        has_visited = current_user.all_visits()
        for item in has_visited:
            if item.composer == composer.name_short:
                visitlist.append(item.id)

    return render_template('composer/composer.html',
                           visitlist=visitlist, search=search, random_work=random_work, filter_method=filter_method,
                           composer=composer, catalogued=catalogued, borndied=borndied, eras=eras, math=math,
                           years=years, svgheight=header.svgheight, works=workslist, title=name, ages=ages, masterpieces=masterpieces)


@bp.route('/composerpanels/<name>')
def composerpanels(name):
    session['composer_view'] = "tables"

    filter_method = request.args.get('filter', "recommended")

    # check if composer has been catalogued or redirect to albums page
    try:
        work = WorkList.query.filter_by(composer=name).first_or_404()
    except:
        return redirect('/composeralbums/' + name + '/1')

    try:
        # get composer information
        composer = ComposerList.query.filter_by(name_short=name).first_or_404()
    except Exception:
        return redirect(url_for('main.index'))

    # user page viewing
    if current_user.is_authenticated:
        current_user.page_viewing = '<a href="' + url_for("composer.composer", name=name) + '">' + composer.name_full + '</a>'
        db.session.commit()

    # get flag
    with open('app/static/countries.json') as f:
        flags = json.load(f)
    flag = flags[composer.nationality]
    flag = flag.lower()
    composer.flagimg = 'flags/1x1/' + flag + '.svg'

    # create chart
    array = []
    array.append(composer)
    header = ComposerHeader(array, composer.born, composer.died)  # change back
    eras = header.generate_eras()
    # retrieve all composer works
    catalogued = []

    if filter_method == "recommended":
        works = WorkList.query.filter_by(composer=name, recommend=True).order_by(WorkList.order, WorkList.genre, WorkList.id).all()
        genre_list = db.session.query(WorkList.genre.distinct()).order_by(WorkList.order, WorkList.genre, WorkList.id)\
            .filter(WorkList.composer == composer.name_short, WorkList.recommend == True)
    elif filter_method == "playable":
        works = db.session.query(WorkList)\
            .join(Spotify, WorkList.id == Spotify.id)\
            .filter_by(composer=name)\
            .order_by(WorkList.order, WorkList.genre, WorkList.id).all()
        # improve this later if less genres than all
        genre_list = db.session.query(WorkList.genre.distinct()).order_by(WorkList.order, WorkList.genre, WorkList.id)\
            .filter(WorkList.composer == composer.name_short)
    else:
        works = WorkList.query.filter_by(composer=name)\
            .order_by(WorkList.order, WorkList.genre, WorkList.id).all()
        workspotify = db.session.query(Spotify)\
            .join(WorkList, WorkList.id == Spotify.id)\
            .options(load_only(Spotify.id))\
            .filter_by(composer=name)
        genre_list = db.session.query(WorkList.genre.distinct()).order_by(WorkList.order, WorkList.genre, WorkList.id)\
            .filter(WorkList.composer == composer.name_short)
        for item in workspotify:
            catalogued.append(item.id)

    if not works:
        abort(404)

    workslist = header.create_chart(works)

    # genre list

    # for random work
    num = random.randint(0, len(workslist) - 1)
    random_work = workslist[num].id

    # get list of which works has_visited
    visitlist = []
    if current_user.is_authenticated:
        has_visited = current_user.all_visits()
        for item in has_visited:
            if item.composer == composer.name_short:
                visitlist.append(item.id)

    # genre split for display rendering
    if filter_method == "recommended":
        num_works = len(works)
        median_work_num = int(math.ceil(num_works / 2))
        median_work_genre = works[median_work_num].genre

        i = 0
        for genre in genre_list:
            i += 1
            if genre[0] == median_work_genre:
                break
        if genre_list.count() > 1:
            split_work_genre = genre_list[i][0]
        else:
            split_work_genre = genre_list[0][0]
    else:
        num_genres = genre_list.count()
        median_genre_num = int(math.ceil(num_genres / 2))
        split_work_genre = genre_list[median_genre_num][0]

    return render_template('composer/composerpanels.html',
                           visitlist=visitlist, random_work=random_work, median_work_genre=split_work_genre, filter_method=filter_method,
                           composer=composer, catalogued=catalogued, eras=eras, math=math,

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/templates/user/_composer.html
<table class="table table-borderless table-condensed">
   <tr>
      <td width="85px">
         <a href="{{ url_for('composer.composer', name=composer.name_short) }}">
         <img class ="favorite-composer-img" src="{{config['STATIC']}}img/{{ composer.name_short }}.jpg" />
         </a>
      </td>
      <td style="vertical-align:middle;">
         <a href="{{ url_for('composer.composer_router', name=composer.name_short)  }}">
         <b>{{ composer.name_full }}</b>
         </a>
         <br>
         {{ composer.description }}
         <br>
         <a href="{{ url_for('user.unfavorite_composer', composerid=composer.id) }}">
         Remove
         </a>
      </td>
   </tr>
</table>

app/templates/user/_message.html
    <tr>
        <td width="43px">
            <a href="{{ url_for('user.user', username=post.author.username) }}">
                <img class="message-avatar" src="{{ post.author.avatar(30)}}" />
            </a>
        </td>
        <td>
            <b><a href="{{ url_for('user.user', username=post.author.username) }}">{{ post.author.display_name }}</a></b>
            {%if post.timestamp > previous_read_time %}
            <span class="badge"> NEW</span>
            {% endif %}
            <span class="pull-right" style="color:#8d95a5">{{ moment(post.timestamp).fromNow()}}</span>
            <br>
            <p style="white-space: pre-line;">{{ post.body }}</p>
            <a href="{{ url_for('user.send_message', recipient=post.author.username) }}">Reply</a>
            <span class="pull-right"><a href="{{ url_for('user.delete_message', message_id=post.id) }}">Delete</a></span>
        </td>
    </tr>

app/templates/user/_sent_message.html
    <tr>
        <td width="43px">
            <a href="{{ url_for('user.user', username=post.author.username) }}">
                <img class="message-avatar" src="{{ post.recipient.avatar(30)}}" />
            </a>
        </td>
        <td>
            Sent to <b><a href="{{ url_for('user.user', username=post.recipient.username) }}">{{ post.recipient.display_name }}</a></b>:
            <span class="pull-right" style="color:#8d95a5">{{ moment(post.timestamp).fromNow()}}</span>
            <br>
            <p style="white-space: pre-line;">{{ post.body }}</p>
            <span class="pull-right"><a href="{{ url_for('user.delete_sent_message', message_id=post.id) }}">Delete</a></span>
        </td>
    </tr>

app/templates/user/_usercomposer.html
<table class="table table-borderless table-condensed">
   <tr>
      <td width="85px">
         <a href="{{ url_for('composer.composer_router', name=composer.name_short) }}">
         <img class ="favorite-composer-img" src="{{config['STATIC']}}img/{{ composer.name_short }}.jpg" />
         </a>
      </td>
      <td style="vertical-align:middle;">
         <a href="{{ url_for('composer.composer_router', name=composer.name_short)  }}">
         <b>{{ composer.name_full }}</b>
         </a>
         <br>
         {{ composer.description }}
         <br>
      </td>
   </tr>
</table>

app/templates/user/_userlikes.html
<div class="rcorners">
 <table class="table table-borderless table-condensed">
   <tr>
      <td width="85px">
         <a href="{{ url_for('albums.albums', work_id=album.work_id) }}">
         <img class ="top-album-img" src="{{album.album_img}}" />
         </a>
      </td>
      <td style="vertical-align:middle;">
         <a href="{{ url_for('albums.albums', work_id=album.work_id) }}">
         <b>{{ album.artists }}</b>
         </a>
         <br>
         {{ album.composer }}: {{ album.work }}
      </td>
   </tr>
</table>
  </div>

app/templates/user/change_avatar.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Change Profile Picture</h1>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
     {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endwith %}

    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <hr>
    <a href="/">Cancel</a>
{% endblock %}

app/templates/user/clear_visits.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Clear Visited Works</h1>
    <div class="alert alert-warning" role="alert">WARNING: This will delete all records of which works you have visited and cannot be undone.</div>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <hr>
    <a href="/">Back to safety</a>
{% endblock %}

app/templates/user/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit Profile</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
        <hr>
    <a href="/">Cancel</a>
{% endblock %}

app/templates/user/favorites.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
.container .jumbotron {
    position: relative;
    background: url("https://storage.googleapis.com/composer-explorer.appspot.com/headers/Piano.jpg") no-repeat center center;
    background-size: cover;
    color: white;
    border-radius: 0px
    border-radius: 6px ;

}
.jumbotron > .overlay {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-image: linear-gradient(to bottom left, rgb(52,58,64, 0.4), rgb(52,58,64, 1));
/*    background-color: rgb(52,58,64, 0.80);*/
    z-index: 1;
    border-radius: 6px ;
}

.jumbotron > .inner {
    position: relative;
    z-index: 2;
}

body{
    background: #f1f2f4;
}

.rcorners{
  border-radius: 6px;
  background: #fff;
  border: 1px solid #d4d7dd;
  padding: 20px;
  padding-bottom: 0px;
  margin-bottom: 10px;
}

</style>

<div class="jumbotron">
    <div class="overlay"></div>
    <div class="inner">
    <h1>My Favorites</h1>
    <h3></h3>
</div>
</div>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% endwith %}

{% for composer in composers %}
<div class="col-lg-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
  <div class="rcorners">
        {% include 'user/_composer.html' %}
  </div>
</div>
{% endfor %}

{% endblock %}

app/templates/user/mass_message.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3>Send mass message to all users</h3>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/messages.html
{% extends "base.html" %}
{% block app_content %}
    <h1>Messages</h1>
<br>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Received</a></li>
  <li role="presentation"><a href="/messages_sent">Sent</a></li>
</ul>


    <table class="table table-hover">
    {% if not messages %}
    <br>
<div class="alert alert-info" role="alert">You have no private messages.</div>
    {% endif %}
    {% for post in messages %}
        {% include 'user/_message.html' %}
    {% endfor %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<br>
     {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endwith %}


</table>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer messages' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Older messages'}} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user/messages_sent.html
{% extends "base.html" %}
{% block app_content %}
    <h1>Messages</h1>
<br>
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/messages">Received</a></li>
  <li role="presentation" class="active"><a href="#">Sent</a></li>
</ul>


    <table class="table table-hover">
    {% if not messages %}
    <br>
<div class="alert alert-info" role="alert">No sent messages.</div>
    {% endif %}
    {% for post in messages %}
        {% include 'user/_sent_message.html' %}
    {% endfor %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<br>
     {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endwith %}


</table>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer messages' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Older messages'}} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user/send_message.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3>Send Message to {{recipient}}</h3>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/user.html
{% extends "base.html" %}
{% block app_content %}
<style>
body{
    background: #f1f2f4;
}
</style>
<div class="panel panel-default">
   <div class="panel-heading">
      <h2><img class="user-page-avatar" src="{{ user.avatar(48) }}">&nbsp;<b> {{ user.display_name }}</b></h2>
   </div>
   <div class="panel-body">
      {% if user.admin %}<p style="color:goldenrod;"><b>Site Administrator</b></p>{% endif %}
      {% if user.about_me %}
      <p>{{ user.about_me }}</p>
      {% endif %}
      {% if user.last_seen %}
      <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
      {% endif %}
   </div>
</div>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-info" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Messages</h3>
   </div>
   <div class="panel-body">
      {% if user == current_user %}
      <p><a href="{{ url_for('user.messages') }}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;&nbsp;View your messages</a></p>
      {% else %}
      <p><a href="{{ url_for('user.send_message', recipient=user.username) }}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;&nbsp;Send private message</a></p>
      {% endif %}
   </div>
</div>
{% if user == current_user %}
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Control Panel</h3>
   </div>
   <div class="panel-body">
      <p><a href="{{ url_for('user.edit_profile') }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;&nbsp;Edit your profile</a></p>
      <p><a href="{{ url_for('user.change_avatar') }}"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;&nbsp;Change profile picture</a></p>
      <p><a href="{{ url_for('user.clear_visits') }}"><span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>&nbsp;&nbsp;Clear visited works</a></p>
      {% if session['premium'] %}
      <p><a href="{{ url_for('spotify.connect_spotify') }}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;&nbsp;Change Spotify device</a></p>
      {% endif %}
   </div>
</div>
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Log Out</h3>
   </div>
   <div class="panel-body">
      <p><a href="{{ url_for('auth.logout') }}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;&nbsp;Log out</a></p>
   </div>
</div>
{% endif %}

<!-- <div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">User Statistics</h3>
   </div>
   <div class="panel-body">
      <div class="col-lg-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
         Forum Posts:
         {{ forum_posts }}
      </div>
      <div class="col-lg-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
         Album Page Comments:
         {{ comments }}
      </div>
   </div>
</div> -->

{% if composers %}
<div class="panel panel-default">
   <div class="panel-heading">
      {% if user.display_name[-1] == "s" %}
      <h3 class="panel-title">{{user.display_name}}' Favorite Composers</h3>
      {% else %}
      <h3 class="panel-title">{{user.display_name}}'s Favorite Composers</h3>
      {% endif %}
   </div>
   <div class="panel-body">
      {% for composer in composers %}
      <div class="col-lg-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
         <div class="rcorners">
            {% include 'user/_usercomposer.html' %}
         </div>
      </div>
      {% endfor %}
   </div>
</div>
{% endif %}

{% if likes %}
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Recently liked by {{user.display_name}}</h3>
   </div>
   <div class="panel-body">
      {% for album in likes %}
      <div class="col-lg-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
         <div class="rcorners">
            {% include 'user/_userlikes.html' %}
         </div>
      </div>
      {% endfor %}
   </div>
</div>
{% endif %}


{% endblock %}